### ISSUE TITLE
where is drishti.py?

### ISSUE THREAD

**Issue by roblatham00** [hpc-io/drishti#1]
I did 'pip install drishti' , but as a regular user.   I don't see any drishti in ${HOME}/.local/bin .  

`./.local/lib/python3.10/site-packages/drishti` only has one `datasets` directory

**Comment by roblatham00** [comment]
Oh, whoops, pip picked up the wrong drishti.  it picked up https://gitlab.com/abhishek.ambastha/computer-vision/tree/master/drishti !

**Comment by jeanbez** [comment]
I've updated the README with the correct `drishti-io` package when installing from pip.
